name: borked3ds-build

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linux-clang-jammy:
    runs-on: ubuntu-22.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: linux
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-
      - name: Remove System Clang
        run: sudo apt autoremove clang-13 clang-format-13 clang-tidy-13 clang-14 clang-format-14 clang-tidy-14 clang-15 clang-format-15 clang-tidy-15 -y
      - name: Install Clang PPA
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main
          repo-name: llvm
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install GCC PPA
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
      - name: Update deb repositories 
        run: sudo apt-get update 
      - name: Install New Packages
        run: sudo apt-get -y install ccache gcc-11 clang-19 clang-tools-19 clang-19-doc libxcb-xkb-dev libclang-common-19-dev libclang-19-dev libclang1-19 clang-format-19 python3-clang-19 clangd-19 clang-tidy-19 && sudo apt-get clean
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - name: Install mold linker
        uses: rui314/setup-mold@v1
        with:
          make-default: true 
      - name: Build
        run: ./.ci/build.sh
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
